steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v0.20.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    skaffold run -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID;
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "cloud-deploy-test",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "artifacts.json"
    ]
