steps:
# Build and tag using commit sha
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/github.com/drvaya-learn/clouddeploy-demo:${COMMIT_SHA}', '-f', 'Dockerfile']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/drvaya-learn/clouddeploy-demo:${COMMIT_SHA}']
# Dynamic Commit-Sha replace
- id: "Store Values"
  name: ubuntu
  entrypoint: bash
  args:
    - -c
    - |
      # Save a value to persistent volume mount: "/workspace"
      sed -e 's/$COMMIT_SHA/'"$COMMIT_SHA"'/g' deployment.yaml > k8s/web.yaml
      # Save another
# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "cloud-deploy-test",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "github.com/drvaya-learn/clouddeploy-demo=gcr.io/$PROJECT_ID/github.com/drvaya-learn/clouddeploy-demo:${COMMIT_SHA}"
    ]
